apiVersion: 1

datasources:
- name: prometheusdata
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: false
  uid: 1
- name: jaeger
  type: jaeger
  access: proxy
  orgId: 1
  url: http://jaeger:16686
  isDefault: false
  version: 1
  editable: false
  uid: 2
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  jsonData:
    maxLines: 1000
    derivedFields:
      - datasourceUid: 2
      - matcherRegex: "traceID=(\\w+)"
        name: TraceID
        url: 'http://jaeger:16686/trace/$${__value.raw}'